apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-l4co
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xjcp-tenant/rhtap-demo-app/hacbs-test-project-l4co@sha256:70c0faf49215db67cfd901fbd1894000f5121d52607c4ec039b7ad2d588ad2cd
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
